source "${HOME}/.zshrc.d/oh-my-zsh.zsh"
source "${HOME}/.zshrc.d/homebrew.zsh"
source "${HOME}/.zshrc.d/go.zsh"
source "${HOME}/.zshrc.d/python.zsh"
source "${HOME}/.zshrc.d/completions.zsh"
source "${HOME}/.zshrc.d/kube.zsh"
