services:
  dotcontainer:
    build: .
    image: localhost/dotcontainer
    command: sleep infinity
    volumes:
      - codex:/home/vscode/.codex
      - dotcontainer-brew:/home/linuxbrew/.linuxbrew
      - dotcontainer-cache:/home/vscode/.cache
      - dotcontainer-share:/home/vscode/.local/share
      - ${DOTFILES}:/mnt/dotfiles:ro
      - ../:/mnt/workspace

volumes:
  codex: {}
  dotcontainer-brew:
    name: dotcontainer-brew
  dotcontainer-cache:
    name: dotcontainer-cache
  dotcontainer-share:
    name: dotcontainer-share
